# Generated by Django 5.0.4 on 2024-05-09 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorManagement', '0002_histperformance_date_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histperformance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 8, 18, 38, 518876)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
