# Generated by Django 5.0.4 on 2024-05-09 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorManagement', '0004_purchaseorder_delivery_date_purchaseorder_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histperformance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 15, 51, 8, 980422)),
        ),
    ]
